name = "dashmsg"
pages_build_output_dir = "./public"
compatibility_date = "2026-03-01"

[[d1_databases]]
binding = "DB"
database_name = "dashmsg_db"
database_id = "ca42317e-102d-4b77-b691-9de86a9a5a2f"

[[r2_buckets]]
binding = "REPORTS_BUCKET"
bucket_name = "dashmsg-reports"